### ISSUE TITLE
Livescript Support?

### ISSUE THREAD

**Issue by legomind** [jashkenas/docco#239]
Hey all, I am trying to document my application written in the amazing livescript (http://livescript.net/), but I am having no success. I get the following error

```
TypeError: Cannot read property 'compiled' of undefined
```

**Comment by smokku** [comment]
According to http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html LiveScript is supported now.

**Comment by neocotic** [comment]
It looks like it's been in highlight.js since v8.3 (latest version is v8.5) which docco's semver dependency (`>= 8.0.x`) will pick up. However, if we're adding this dependency to an v8.3 feature we should change this to at least `>= 8.3.x`.

I'm sure a PR to propose the necessary changes would be welcomed by the maintainers if you're volunteering :smile:
